# Generated by Django 5.1.1 on 2024-10-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Samarqand , Oq oltin', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='998997654321', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='998991234567', max_length=12),
        ),
    ]
